//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGiaiTrii.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int ID { get; set; }
        public string NameAnimals { get; set; }
        public string ImageA01 { get; set; }
        public string NoteA { get; set; }
        public string BlogA { get; set; }
    }
}
