//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGiaiTrii.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class entertainmentEntities2 : DbContext
    {
        public entertainmentEntities2()
            : base("name=entertainmentEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Nature> Natures { get; set; }
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<House> Houses { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<Distributive> Distributives { get; set; }
    }
}
