//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGiaiTrii.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nature
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Note { get; set; }
        public string Blog { get; set; }
        public string Imagee { get; set; }
        public string Image03 { get; set; }
        public string Image04 { get; set; }
    }
}
